image recognition
eliasjlara/PUM-04 pull request #154
Opened 2024-05-03 14:32 UTC by thulavall

**WHY?** 
Aida image recognition functionality is to  be part of the final product.

**WHAT?**
AIDA image recognition funcitonality...

2024-05-03 16:04 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/image_recognition/image_recognition/video_analyzer.py
Fix the todo before the pull request is approved

2024-05-03 16:05 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/image_recognition/package.xml
Add Albin as maintainer of the node

2024-05-03 16:06 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/image_recognition/test/test_flake8.py
Believe we have removed this test for all other packages. Should be removed.

2024-05-03 16:06 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/image_recognition/test/test_pep257.py
Believe we have removed this test for all other packages. Should be removed.

2024-05-03 16:08 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/video/test/test_copyright.py
Believe we have removed this test for all other packages. Should be removed.

2024-05-03 16:08 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/video/test/test_flake8.py
Believe we have removed this test for all other packages. Should be removed.

2024-05-03 16:08 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/video/test/test_pep257.py
Believe we have removed this test for all other packages. Should be removed.

2024-05-03 16:08 UTC, alexanderortengren commented on README.md
Can't see what has changed, but should be fine

2024-05-03 16:11 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/video/video/web_video.py
The docstring does not seem to correctly describe the node. 
Functions needs docstrings as well

2024-05-03 16:13 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/video/video/video_viewer.py
Test node? If so create a folder called test_nodes to make it easier to distinguish. If not write docstrings.

2024-05-03 16:14 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/video/video/camera_video.py
Write docstrings for files.

2024-05-03 16:15 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/image_recognition/image_recognition/video_analyzer.py
Also add docstrings for functions to make it easier for next project group to understand what the class and functions are doing

2024-05-03 16:19 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/image_recognition/image_recognition/gesture_recognizer.py
You set all the variables in the init function of the class then call setup which in turn just calls the setup_camera_feed. Can we remove one step here?

2024-05-03 16:22 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/image_recognition/image_recognition/pose_landmarker.py
Mostly the same comments as in gesture_recognizer. Add docstrings for node and functions. 
Is the model path hardcoded or does it work on another systems? The setup functions seems to be deprecated as you just call the setup_camera_feed with variables set in init.

2024-05-03 16:24 UTC, alexanderortengren requested changes
See comments on files. We also have no tests at all, not even trivial tests.

2024-05-09 09:43 UTC, thulavall commented on AIDA/ros2_humble_ws/src/image_recognition/image_recognition/video_analyzer.py
done

2024-05-09 09:44 UTC, thulavall commented on AIDA/ros2_humble_ws/src/image_recognition/package.xml
done

2024-05-09 09:44 UTC, thulavall commented on AIDA/ros2_humble_ws/src/image_recognition/test/test_copyright.py
done

2024-05-09 09:45 UTC, thulavall commented on AIDA/ros2_humble_ws/src/image_recognition/test/test_flake8.py
done

2024-05-09 09:48 UTC, thulavall commented on AIDA/ros2_humble_ws/src/image_recognition/setup.py
done

2024-05-09 09:48 UTC, thulavall commented on AIDA/ros2_humble_ws/src/video/test/test_copyright.py
done

2024-05-09 09:48 UTC, thulavall commented on AIDA/ros2_humble_ws/src/video/test/test_flake8.py
done

2024-05-09 09:48 UTC, thulavall commented on AIDA/ros2_humble_ws/src/video/test/test_pep257.py
done

2024-05-09 12:06 UTC, thulavall commented on AIDA/ros2_humble_ws/src/video/video/video_viewer.py
I removed the node. It was a test node that is not needed anymore.

2024-05-09 12:07 UTC, thulavall commented on AIDA/ros2_humble_ws/src/image_recognition/image_recognition/gesture_recognizer.py
done

2024-05-10 18:15 UTC, alexanderortengren approved these changes
Is approved. But how are we supposed to remember to remove hardcoded path for the models?

2024-05-10 18:16 UTC, alexanderortengren commented on AIDA/ros2_humble_ws/src/video/video/video_viewer.py
Maybe still have it in project for easy testing?

2024-05-13 06:56 UTC, thulavall commented
I'll add a ticket for the removal of hardcoded paths

2024-05-13 06:56 UTC, merged